version: '{build}'
skip_tags: true
image:
  - Visual Studio 2022
  - Ubuntu2204
configuration: Release
build_script:
- ps: ./Build.ps1
for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
    - sh build.sh
test: false
artifacts:
- path: artifacts/Serilog.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: sl+QD7Cj+E9sIAAUYEwPT+1l9ZdBgA7dlPJ7DYcDO+hAj8ytP/+VGgWruNS1Iqge
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: 1n3WuHyRnk+rX8pH5xy0mCX64b/XbxgA+aHle8s4wP9ZMKrhcJ+FGecNtfb7QNKf
  artifact: /Serilog.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
